#!/bin/bash -x

# Loads text data for buoys off the SE US coast into Kafka, serially

# Pre-req:              Data files have been downloaded to the the data directory
# Post-condition:       Historical data for these buoys is in its Kafka topic. E.g.: 41010-TXT

# To prep these for the WxStream application, run com.ubiquibit.buoy.jobs.util.StageFeeds.scala

readonly SPARK_HOME="/Users/jason/sbin/spark-2.4.0-bin-hadoop2.7" ;
readonly SPARK_HOST="Flob.local" ;
readonly SRCDIR="/Users/jason/scratch/sensor-failure" ;

# Note: 16 seems to be a good pause for my machine. If you see things backing up in the SparkUI, back it off to a larger number...

# You can verify it worked, by using: ${KAFKA_HOME}/bin/kafka-console-consumer.sh --bootstrap-server ${KAFKA_HOST}:9092 --topic 41139-TXT --from-beginning

/bin/bash ${SPARK_HOME}/bin/spark-submit --class "com.ubiquibit.buoy.jobs.setup.InitKafkaImpl" --master "spark://${SPARK_HOST}:7077" --deploy-mode cluster --executor-cores 2 --packages "org.apache.spark:spark-sql-kafka-0-10_2.11:2.4.0" "${SRCDIR}/target/scala-2.11/sensorfailure-assembly-1.0.jar" 41002 ; sleep 16 ;
/bin/bash ${SPARK_HOME}/bin/spark-submit --class "com.ubiquibit.buoy.jobs.setup.InitKafkaImpl" --master "spark://${SPARK_HOST}:7077" --deploy-mode cluster --executor-cores 2 --packages "org.apache.spark:spark-sql-kafka-0-10_2.11:2.4.0" "${SRCDIR}/target/scala-2.11/sensorfailure-assembly-1.0.jar" 41004 ; sleep 16 ;
/bin/bash ${SPARK_HOME}/bin/spark-submit --class "com.ubiquibit.buoy.jobs.setup.InitKafkaImpl" --master "spark://${SPARK_HOST}:7077" --deploy-mode cluster --executor-cores 2 --packages "org.apache.spark:spark-sql-kafka-0-10_2.11:2.4.0" "${SRCDIR}/target/scala-2.11/sensorfailure-assembly-1.0.jar" 41008 ; sleep 16 ;
/bin/bash ${SPARK_HOME}/bin/spark-submit --class "com.ubiquibit.buoy.jobs.setup.InitKafkaImpl" --master "spark://${SPARK_HOST}:7077" --deploy-mode cluster --executor-cores 2 --packages "org.apache.spark:spark-sql-kafka-0-10_2.11:2.4.0" "${SRCDIR}/target/scala-2.11/sensorfailure-assembly-1.0.jar" 41009 ; sleep 16 ;
/bin/bash ${SPARK_HOME}/bin/spark-submit --class "com.ubiquibit.buoy.jobs.setup.InitKafkaImpl" --master "spark://${SPARK_HOST}:7077" --deploy-mode cluster --executor-cores 2 --packages "org.apache.spark:spark-sql-kafka-0-10_2.11:2.4.0" "${SRCDIR}/target/scala-2.11/sensorfailure-assembly-1.0.jar" 41010 ; sleep 16 ;
/bin/bash ${SPARK_HOME}/bin/spark-submit --class "com.ubiquibit.buoy.jobs.setup.InitKafkaImpl" --master "spark://${SPARK_HOST}:7077" --deploy-mode cluster --executor-cores 2 --packages "org.apache.spark:spark-sql-kafka-0-10_2.11:2.4.0" "${SRCDIR}/target/scala-2.11/sensorfailure-assembly-1.0.jar" 41013 ; sleep 16 ;
/bin/bash ${SPARK_HOME}/bin/spark-submit --class "com.ubiquibit.buoy.jobs.setup.InitKafkaImpl" --master "spark://${SPARK_HOST}:7077" --deploy-mode cluster --executor-cores 2 --packages "org.apache.spark:spark-sql-kafka-0-10_2.11:2.4.0" "${SRCDIR}/target/scala-2.11/sensorfailure-assembly-1.0.jar" 41024 ; sleep 16 ;
/bin/bash ${SPARK_HOME}/bin/spark-submit --class "com.ubiquibit.buoy.jobs.setup.InitKafkaImpl" --master "spark://${SPARK_HOST}:7077" --deploy-mode cluster --executor-cores 2 --packages "org.apache.spark:spark-sql-kafka-0-10_2.11:2.4.0" "${SRCDIR}/target/scala-2.11/sensorfailure-assembly-1.0.jar" 41026 ; sleep 16 ;
/bin/bash ${SPARK_HOME}/bin/spark-submit --class "com.ubiquibit.buoy.jobs.setup.InitKafkaImpl" --master "spark://${SPARK_HOST}:7077" --deploy-mode cluster --executor-cores 2 --packages "org.apache.spark:spark-sql-kafka-0-10_2.11:2.4.0" "${SRCDIR}/target/scala-2.11/sensorfailure-assembly-1.0.jar" 41029 ; sleep 16 ;
/bin/bash ${SPARK_HOME}/bin/spark-submit --class "com.ubiquibit.buoy.jobs.setup.InitKafkaImpl" --master "spark://${SPARK_HOST}:7077" --deploy-mode cluster --executor-cores 2 --packages "org.apache.spark:spark-sql-kafka-0-10_2.11:2.4.0" "${SRCDIR}/target/scala-2.11/sensorfailure-assembly-1.0.jar" 41033 ; sleep 16 ;
/bin/bash ${SPARK_HOME}/bin/spark-submit --class "com.ubiquibit.buoy.jobs.setup.InitKafkaImpl" --master "spark://${SPARK_HOST}:7077" --deploy-mode cluster --executor-cores 2 --packages "org.apache.spark:spark-sql-kafka-0-10_2.11:2.4.0" "${SRCDIR}/target/scala-2.11/sensorfailure-assembly-1.0.jar" 41037 ; sleep 16 ;
/bin/bash ${SPARK_HOME}/bin/spark-submit --class "com.ubiquibit.buoy.jobs.setup.InitKafkaImpl" --master "spark://${SPARK_HOST}:7077" --deploy-mode cluster --executor-cores 2 --packages "org.apache.spark:spark-sql-kafka-0-10_2.11:2.4.0" "${SRCDIR}/target/scala-2.11/sensorfailure-assembly-1.0.jar" 41038 ; sleep 16 ;
/bin/bash ${SPARK_HOME}/bin/spark-submit --class "com.ubiquibit.buoy.jobs.setup.InitKafkaImpl" --master "spark://${SPARK_HOST}:7077" --deploy-mode cluster --executor-cores 2 --packages "org.apache.spark:spark-sql-kafka-0-10_2.11:2.4.0" "${SRCDIR}/target/scala-2.11/sensorfailure-assembly-1.0.jar" 41040 ; sleep 16 ;
/bin/bash ${SPARK_HOME}/bin/spark-submit --class "com.ubiquibit.buoy.jobs.setup.InitKafkaImpl" --master "spark://${SPARK_HOST}:7077" --deploy-mode cluster --executor-cores 2 --packages "org.apache.spark:spark-sql-kafka-0-10_2.11:2.4.0" "${SRCDIR}/target/scala-2.11/sensorfailure-assembly-1.0.jar" 41041 ; sleep 16 ;
/bin/bash ${SPARK_HOME}/bin/spark-submit --class "com.ubiquibit.buoy.jobs.setup.InitKafkaImpl" --master "spark://${SPARK_HOST}:7077" --deploy-mode cluster --executor-cores 2 --packages "org.apache.spark:spark-sql-kafka-0-10_2.11:2.4.0" "${SRCDIR}/target/scala-2.11/sensorfailure-assembly-1.0.jar" 41043 ; sleep 16 ;
/bin/bash ${SPARK_HOME}/bin/spark-submit --class "com.ubiquibit.buoy.jobs.setup.InitKafkaImpl" --master "spark://${SPARK_HOST}:7077" --deploy-mode cluster --executor-cores 2 --packages "org.apache.spark:spark-sql-kafka-0-10_2.11:2.4.0" "${SRCDIR}/target/scala-2.11/sensorfailure-assembly-1.0.jar" 41044 ; sleep 16 ;
/bin/bash ${SPARK_HOME}/bin/spark-submit --class "com.ubiquibit.buoy.jobs.setup.InitKafkaImpl" --master "spark://${SPARK_HOST}:7077" --deploy-mode cluster --executor-cores 2 --packages "org.apache.spark:spark-sql-kafka-0-10_2.11:2.4.0" "${SRCDIR}/target/scala-2.11/sensorfailure-assembly-1.0.jar" 41046 ; sleep 16 ;
/bin/bash ${SPARK_HOME}/bin/spark-submit --class "com.ubiquibit.buoy.jobs.setup.InitKafkaImpl" --master "spark://${SPARK_HOST}:7077" --deploy-mode cluster --executor-cores 2 --packages "org.apache.spark:spark-sql-kafka-0-10_2.11:2.4.0" "${SRCDIR}/target/scala-2.11/sensorfailure-assembly-1.0.jar" 41047 ; sleep 16 ;
/bin/bash ${SPARK_HOME}/bin/spark-submit --class "com.ubiquibit.buoy.jobs.setup.InitKafkaImpl" --master "spark://${SPARK_HOST}:7077" --deploy-mode cluster --executor-cores 2 --packages "org.apache.spark:spark-sql-kafka-0-10_2.11:2.4.0" "${SRCDIR}/target/scala-2.11/sensorfailure-assembly-1.0.jar" 41049 ; sleep 16 ;
/bin/bash ${SPARK_HOME}/bin/spark-submit --class "com.ubiquibit.buoy.jobs.setup.InitKafkaImpl" --master "spark://${SPARK_HOST}:7077" --deploy-mode cluster --executor-cores 2 --packages "org.apache.spark:spark-sql-kafka-0-10_2.11:2.4.0" "${SRCDIR}/target/scala-2.11/sensorfailure-assembly-1.0.jar" 41052 ; sleep 16 ;
/bin/bash ${SPARK_HOME}/bin/spark-submit --class "com.ubiquibit.buoy.jobs.setup.InitKafkaImpl" --master "spark://${SPARK_HOST}:7077" --deploy-mode cluster --executor-cores 2 --packages "org.apache.spark:spark-sql-kafka-0-10_2.11:2.4.0" "${SRCDIR}/target/scala-2.11/sensorfailure-assembly-1.0.jar" 41053 ; sleep 16 ;
/bin/bash ${SPARK_HOME}/bin/spark-submit --class "com.ubiquibit.buoy.jobs.setup.InitKafkaImpl" --master "spark://${SPARK_HOST}:7077" --deploy-mode cluster --executor-cores 2 --packages "org.apache.spark:spark-sql-kafka-0-10_2.11:2.4.0" "${SRCDIR}/target/scala-2.11/sensorfailure-assembly-1.0.jar" 41056 ; sleep 16 ;
/bin/bash ${SPARK_HOME}/bin/spark-submit --class "com.ubiquibit.buoy.jobs.setup.InitKafkaImpl" --master "spark://${SPARK_HOST}:7077" --deploy-mode cluster --executor-cores 2 --packages "org.apache.spark:spark-sql-kafka-0-10_2.11:2.4.0" "${SRCDIR}/target/scala-2.11/sensorfailure-assembly-1.0.jar" 41064 ; sleep 16 ;
/bin/bash ${SPARK_HOME}/bin/spark-submit --class "com.ubiquibit.buoy.jobs.setup.InitKafkaImpl" --master "spark://${SPARK_HOST}:7077" --deploy-mode cluster --executor-cores 2 --packages "org.apache.spark:spark-sql-kafka-0-10_2.11:2.4.0" "${SRCDIR}/target/scala-2.11/sensorfailure-assembly-1.0.jar" 41108 ; sleep 16 ;
/bin/bash ${SPARK_HOME}/bin/spark-submit --class "com.ubiquibit.buoy.jobs.setup.InitKafkaImpl" --master "spark://${SPARK_HOST}:7077" --deploy-mode cluster --executor-cores 2 --packages "org.apache.spark:spark-sql-kafka-0-10_2.11:2.4.0" "${SRCDIR}/target/scala-2.11/sensorfailure-assembly-1.0.jar" 41110 ; sleep 16 ;
/bin/bash ${SPARK_HOME}/bin/spark-submit --class "com.ubiquibit.buoy.jobs.setup.InitKafkaImpl" --master "spark://${SPARK_HOST}:7077" --deploy-mode cluster --executor-cores 2 --packages "org.apache.spark:spark-sql-kafka-0-10_2.11:2.4.0" "${SRCDIR}/target/scala-2.11/sensorfailure-assembly-1.0.jar" 41112 ; sleep 16 ;
/bin/bash ${SPARK_HOME}/bin/spark-submit --class "com.ubiquibit.buoy.jobs.setup.InitKafkaImpl" --master "spark://${SPARK_HOST}:7077" --deploy-mode cluster --executor-cores 2 --packages "org.apache.spark:spark-sql-kafka-0-10_2.11:2.4.0" "${SRCDIR}/target/scala-2.11/sensorfailure-assembly-1.0.jar" 41113 ; sleep 16 ;
/bin/bash ${SPARK_HOME}/bin/spark-submit --class "com.ubiquibit.buoy.jobs.setup.InitKafkaImpl" --master "spark://${SPARK_HOST}:7077" --deploy-mode cluster --executor-cores 2 --packages "org.apache.spark:spark-sql-kafka-0-10_2.11:2.4.0" "${SRCDIR}/target/scala-2.11/sensorfailure-assembly-1.0.jar" 41114 ; sleep 16 ;
/bin/bash ${SPARK_HOME}/bin/spark-submit --class "com.ubiquibit.buoy.jobs.setup.InitKafkaImpl" --master "spark://${SPARK_HOST}:7077" --deploy-mode cluster --executor-cores 2 --packages "org.apache.spark:spark-sql-kafka-0-10_2.11:2.4.0" "${SRCDIR}/target/scala-2.11/sensorfailure-assembly-1.0.jar" 41115 ; sleep 16 ;
/bin/bash ${SPARK_HOME}/bin/spark-submit --class "com.ubiquibit.buoy.jobs.setup.InitKafkaImpl" --master "spark://${SPARK_HOST}:7077" --deploy-mode cluster --executor-cores 2 --packages "org.apache.spark:spark-sql-kafka-0-10_2.11:2.4.0" "${SRCDIR}/target/scala-2.11/sensorfailure-assembly-1.0.jar" 41117 ; sleep 16 ;
/bin/bash ${SPARK_HOME}/bin/spark-submit --class "com.ubiquibit.buoy.jobs.setup.InitKafkaImpl" --master "spark://${SPARK_HOST}:7077" --deploy-mode cluster --executor-cores 2 --packages "org.apache.spark:spark-sql-kafka-0-10_2.11:2.4.0" "${SRCDIR}/target/scala-2.11/sensorfailure-assembly-1.0.jar" 41139 ; sleep 16 ;
/bin/bash ${SPARK_HOME}/bin/spark-submit --class "com.ubiquibit.buoy.jobs.setup.InitKafkaImpl" --master "spark://${SPARK_HOST}:7077" --deploy-mode cluster --executor-cores 2 --packages "org.apache.spark:spark-sql-kafka-0-10_2.11:2.4.0" "${SRCDIR}/target/scala-2.11/sensorfailure-assembly-1.0.jar" 41159 ; sleep 16 ;
/bin/bash ${SPARK_HOME}/bin/spark-submit --class "com.ubiquibit.buoy.jobs.setup.InitKafkaImpl" --master "spark://${SPARK_HOST}:7077" --deploy-mode cluster --executor-cores 2 --packages "org.apache.spark:spark-sql-kafka-0-10_2.11:2.4.0" "${SRCDIR}/target/scala-2.11/sensorfailure-assembly-1.0.jar" 41NT0 ; sleep 16 ;
